### ISSUE TITLE
Can jinsta run on a Mac?

### ISSUE THREAD

**Issue by sharmanshah** [breuerfelix/jinsta#77]
I've installed nodejs but everytime I run jinsta I'm asked to enter sms / email code. After entering the code, I get an error. I would appreciate it if someone can share documentation or post a video on how to install and run jinsta on a Mac. Thanks in advance.

Here's the error:

`sharman@iMac sps_jinsta % jinsta -u ******* -p ***** -w ./jinsta_data -t vegan -likelimit 30
info:    logging in with user: ******** ...
? Enter sms / email code: 062874
(node:3711) UnhandledPromiseRejectionWarning: IgLoginRequiredError: GET /api/v1/loom/fetch_config/ - 403 Forbidden; login_required
    at Request.handleResponseError (/usr/local/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:93:24)
    at Request.send (/usr/local/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
    at async LoomRepository.fetchConfig (/usr/local/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/repositories/loom.repository.js:6:26)
(node:3711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3711) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by breuerfelix** [comment]
i just fixed this issue in the latest version some minutes ago :)

can you update and try again please ? and show me the output of `jinsta -v` so i know that you run the latest version :)

**Comment by die-tueftelei** [comment]
I had the same issue - with the update & !! disabling 2factor authentication it now works fine :-)

**Comment by sharmanshah** [comment]
@breuerfelix I updated to 0.0.37 but the errors continue.

sharman@iMac sps_jinsta % jinsta -v
0.0.37
sharman@iMac sps_jinsta % node index.js
info:    logging in with user: sharman.shah ...
? Enter sms / email code: 934081
(node:9600) UnhandledPromiseRejectionWarning: IgLoginRequiredError: GET /api/v1/direct_v2/inbox/?visual_message_return_type=unseen&thread_message_limit=10&persistentBadging=true&limit=20 - 403 Forbidden; login_required
    at Request.handleResponseError (/Users/sharman/sps_jinsta/node_modules/instagram-private-api/dist/core/request.js:93:24)
    at Request.send (/Users/sharman/sps_jinsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
    at async DirectInboxFeed.request (/Users/sharman/sps_jinsta/node_modules/instagram-private-api/dist/feeds/direct-inbox.feed.js:21:26)
(node:9600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sharmanshah** [comment]
@die-tueftelei on my phone, I checked Settings>Security>Two-factor authentication but it already seems to be off and it's asking me to set up Two-factor authentication. Can you guide me how you managed to disable it?

**Comment by die-tueftelei** [comment]
Exactly there in the app I had activated it previously.. As I found no other possibility I remembered I activated that feature 2 month before.. Now my login issues with jinsta are solved..

**Comment by sharmanshah** [comment]
It's been over a month now and I'm still unable to login. My Two-factor authentication is switched off.
1. Should 2FA be on or off?
2. If it's supposed to be on, should 2FA be set to 'Text message' or 'Authentication app'?
